// Belts
export const FETCH_BELTS = 'FETCH_BELTS';
export const BELT_SELECTED = 'BELT_SELECTED';

// Techniques
export const FETCH_TECHNIQUES = 'FETCH_TECHNIQUES';
export const GET_SELECTED_TECHNIQUE_DATA = 'GET_SELECTED_TECHNIQUE_DATA';